# Generated by Django 5.0 on 2025-01-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundimg',
            field=models.ImageField(default='blank-profile.png', upload_to='profile_images'),
        ),
    ]
